### ISSUE TITLE
I've tried to integrate the latest version of your build but...

### ISSUE THREAD

**Issue by ydeshayes** [evopark/Acktie-Mobile-Android-QR-Reader#1]
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/acktie/mobile/android/camera/CameraCallback;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:685)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:230)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:199)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:103)
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/zxing/aztec/AztecDetectorResult;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:685)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:230)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:199)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:103)
[ERROR] :  2 errors; aborting
[ERROR] Application Installer abnormal process termination. Process exit value was 1

**Comment by milgner** [comment]
Have you tried removing the old module first before unpacking the new version? I fear there may be some files left that aren't required anymore.

**Comment by ydeshayes** [comment]
I've delete the other version and it's working now !
